name: Build

on:
  push:
    branches:
      - master

permissions:
  contents: write

jobs:
  linux-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'liberica'
          java-package: 'jdk+fx'
          architecture: 'x64'
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
      - name: Build with Gradle
        run: |
          java -version
          chmod +x ./gradlew
          ./gradlew -version
          ./gradlew clean
          ./gradlew createInstallers
      - name: Set up variables
        id: vars
        run: |
          echo "date_now=$(date +"%Y-%m-%d %T")" >> "${GITHUB_OUTPUT}"
      - name: Upload builds to Releases
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          artifactErrorsFailBuild: true
          artifacts: build/libs/installers/fx-spring*
          body: |
            **This is an automatically generated in-development pre-release version of the application, that includes the latest master branch changes.**
            **⚠️ This build is not stable and may end up terminating with a fatal error. ⚠️**
            **Use at your own risk.**

            - Last build date: `${{steps.vars.outputs.date_now}}`
            - Reference commit: ${{github.sha}}
          name: Development build
          removeArtifacts: true
          tag: dev-build
  windows-build:
    runs-on: windows-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v4
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'liberica'
          java-package: 'jdk+fx'
          architecture: 'x64'
      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
      - name: Compile .ISS to .EXE Installer
        uses: Minionguyjpro/Inno-Setup-Action@v1.2.2
      - name: Build with Gradle
        run: |
          java -version
          gradlew.bat -version
          gradlew.bat clean
          gradlew.bat createInstallers
      - name: Set up variables
        id: vars
        run: |
          echo "date_now=$(date +"%Y-%m-%d %T")" >> "${GITHUB_OUTPUT}"
      - name: Upload builds to Releases
        uses: ncipollo/release-action@v1
        with:
          allowUpdates: true
          artifactErrorsFailBuild: true
          artifacts: build/libs/*.jar
          body: |
            **This is an automatically generated in-development pre-release version of the application, that includes the latest master branch changes.**
            **⚠️ This build is not stable and may end up terminating with a fatal error. ⚠️**
            **Use at your own risk.**

            - Last build date: `${{steps.vars.outputs.date_now}}`
            - Reference commit: ${{github.sha}}
          name: Development build
          removeArtifacts: true
          tag: dev-build